Repository kimyouknow/codesquad-airbnb, pull requests merged in 2022-06, with the labels that each got.

#21 [PR] 2주차 첫번째 PR 리뷰 반영
  FE/.eslintrc.json
  FE/src/components/Calendar/index.tsx
  FE/src/components/Calendar/style.js
  FE/src/components/PriceChart/index.tsx
  FE/src/constants/constants.js
Labels: refactor, FE

#24 [Feat] 달력 무한 캐러셀 우측 구현
  FE/src/components/CalendarModal/index.tsx
  FE/src/components/CalendarModal/style.js
Labels: feat, FE

#23 [Feat] 차트 그래프 최소,최대에 따른 색칠
  .gitignore
  FE/src/App.tsx
  FE/src/components/CanvasLineCharts/index.tsx
  FE/src/components/Chart/index.tsx
  FE/src/components/PriceChart/index.tsx
  FE/src/components/PriceChart/style.js
  FE/src/components/SVGLineChart/index.tsx
Labels: feat, FE

#27 [Refactor] 달력 컴포넌트에서 styled 분리
  FE/src/components/CalendarModal/index.tsx
  FE/src/components/CalendarModal/style.js
Labels: refactor, FE

#28 [Refactor] 차트 그래프 색칠 리팩토링
  FE/src/components/Chart/index.tsx
  FE/src/components/PriceChart/index.tsx
Labels: refactor, FE

#30 [Refactor] 캘린더 우측 클릭시 렌더링 리팩토링
  FE/src/components/CalendarModal/constants.js
  FE/src/components/CalendarModal/index.tsx
  FE/src/components/CalendarModal/style.js
Labels: feat, FE

#35 [Feat] 가격 범위 차트에 양방향 슬라이더 구현
  FE/src/components/Chart/index.tsx
  FE/src/components/PriceChart/index.tsx
  FE/src/components/PriceChart/style.js
  FE/src/style/index.js
Labels: feat, FE

#34 [Refactor] 캘린더 좌측 클릭시 렌더링 및 리팩토링
  FE/package-lock.json
  FE/package.json
  FE/src/components/CalendarCourousel/Calendar/index.tsx
  FE/src/components/CalendarCourousel/Calendar/style.ts
  FE/src/components/CalendarCourousel/constants.ts
  FE/src/components/CalendarCourousel/index.tsx
  FE/src/components/CalendarCourousel/style.ts
  FE/src/components/CalendarModal/constants.js
  FE/src/components/CalendarModal/index.tsx
Labels: feat, refactor, FE

#38 Feat: 캘린더 Date Picker 체크인, 체크아웃 날짜 설정
  FE/src/components/CalendarCourousel/Calendar/index.tsx
  FE/src/components/CalendarCourousel/index.tsx
Labels: feat, FE

#43 [Refactor & Feat] SearchBox 폴더 생성 및 모달 컴포넌트 수정
  FE/src/App.tsx
  FE/src/components/CalendarModal/index.tsx
  FE/src/components/Modal/Potal.tsx
  FE/src/components/Modal/index.tsx
  FE/src/components/Modal/style.ts
  FE/src/components/SearchBox/CalendarArea/CalendarCourousel/Calendar/index.tsx
  FE/src/components/SearchBox/CalendarArea/CalendarCourousel/Calendar/style.ts
  FE/src/components/SearchBox/CalendarArea/CalendarCourousel/constants.ts
  FE/src/components/SearchBox/CalendarArea/CalendarCourousel/index.tsx
  FE/src/components/SearchBox/CalendarArea/CalendarCourousel/style.ts
  FE/src/components/SearchBox/CalendarArea/index.tsx
  FE/src/components/SearchBox/PeopleArea/index.tsx
  FE/src/components/SearchBox/PriceArea/PriceChart/Chart/index.tsx
  FE/src/components/SearchBox/PriceArea/PriceChart/Chart/util.ts
  FE/src/components/SearchBox/PriceArea/PriceChart/MultiRangerSlider/index.tsx
  FE/src/components/SearchBox/PriceArea/PriceChart/MultiRangerSlider/style.ts
  FE/src/components/SearchBox/PriceArea/PriceChart/PriceInfo/index.tsx
  FE/src/components/SearchBox/PriceArea/PriceChart/constants.js
  FE/src/components/SearchBox/PriceArea/PriceChart/index.tsx
  FE/src/components/SearchBox/PriceArea/PriceChart/style.ts
  FE/src/components/SearchBox/PriceArea/index.tsx
  FE/src/components/SearchBox/index.tsx
  FE/src/components/SearchBox/style.ts
  FE/src/components/WindowModal/Portal/index.tsx
  FE/src/components/WindowModal/index.tsx
  FE/src/components/WindowModal/style.js
  FE/src/context/Modals/actions.ts
  FE/src/context/Modals/index.tsx
  FE/src/data/chartData.ts
  FE/src/hoc/WithModal.tsx
  FE/src/hooks/useScrollLock.ts
Labels: feat, refactor, FE
