Repository kimyouknow/codesquad-airbnb, pull requests merged in 2022-05, with the labels that each got.

#6 [Build] 개발환경 세팅
  FE/.eslintrc.json
  FE/.gitignore
  FE/.prettierrc
  FE/README.md
  FE/babel.config.json
  FE/config/webpack.common.js
  FE/config/webpack.development.js
  FE/config/webpack.production.js
  FE/package-lock.json
  FE/package.json
  FE/public/index.html
  FE/src/App.tsx
  FE/src/components/Card.tsx
  FE/src/index.tsx
  FE/tsconfig.json
Labels: FE, build

#8 [Feat] 모달 구현
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  FE/package-lock.json
  FE/package.json
  FE/public/index.html
  FE/src/App.tsx
  FE/src/components/Card.tsx
  FE/src/components/LoginModal/index.jsx
  FE/src/components/WindowModal/Portal/index.tsx
  FE/src/components/WindowModal/index.tsx
  FE/src/components/WindowModal/style.js
  FE/src/hooks/useToggle.ts
  FE/webpack.common.js
  FE/webpack.development.js
  FE/webpack.production.js
Labels: feat, FE

#11 [feat] 캘린더 한 달 뷰
  FE/src/App.tsx
  FE/src/components/Calendar/index.tsx
  FE/src/components/Calendar/style.js
  FE/src/components/CalendarModal/index.tsx
  FE/src/constants/constants.js
Labels: feat, FE

#12 [feat] 차트 레이아웃 시도 (svg, canvas)
  FE/src/App.tsx
  FE/src/components/CanvasLineCharts/index.tsx
  FE/src/components/SVGLineChart/index.tsx
Labels: feat, FE

#14 [PR] 1주차 두번째 PR 리뷰 반영
  FE/public/index.html
  FE/src/components/CalendarModal/index.tsx
  FE/src/components/WindowModal/Portal/index.tsx
  FE/src/components/WindowModal/index.tsx
  FE/src/hooks/useToggle.ts
  FE/webpack.development.js
Labels: refactor, FE

#17 [Feat] 캘린더 렌더링 로직 구현
  FE/src/components/Calendar/index.tsx
  FE/src/components/CalendarModal/index.tsx
  FE/src/components/WindowModal/style.js
  FE/src/constants/constants.js
Labels: feat, FE

#18 [Feat] 차트 그래프 기본 구현
  FE/src/App.tsx
  FE/src/components/PriceChart/constants.js
  FE/src/components/PriceChart/index.tsx
  FE/src/components/PriceChart/mixins.js
  FE/src/components/PriceChart/style.js
Labels: feat, FE
